version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=openapi
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=openapi
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
